config/routes.rb
MyStore::Application.routes.draw do

  resources :items  do
    get :upvote,    on: :member
    get :expensive, on: :collection
  end

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  attr_accessible :title, :body
  has_many :comments, as: :commentable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
  has_many   :positions
  has_many   :items, through:  :positions
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :user_id, :body, :commentable_id, :commentable_type
  belongs_to      :user
  belongs_to      :commentable, polymorphic: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :price, :name, :real, :weight, :description
  validates       :price, numericality: {:greater_than => 0, :allow_nil => 1}
  validates       :name, :description, :price, presence: true

  #belongs_to :category

  after_initialize {}       #Item.new, Item.first
  after_save{} #create,save,update_attributes
  after_create{}
  after_update{}
  after_destroy{}       #item.destroy

  has_many :positions
  has_many :carts, through:  :positions
  has_many :comments, as: :commentable
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible         :user, :user_id
  belongs_to              :user

end

app/models/position.rb
class Position < ActiveRecord::Base
  attr_accessible :item_id, :cart_id, :quantity

  belongs_to :item
  belongs_to :cart
end

app/models/user.rb
class User < ActiveRecord::Base


  attr_accessible :login
  has_one         :cart
  has_many        :orders
  has_many        :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



  protect_from_forgery

 private
  def render_403
      render file: "public/403.html" , status: 403
  end

  def render_404
    render file: "public/404.html" , status: 404
  end

 def check_if_admin
   render_403 unless !params[:admin]
 end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :find_item, only:[:show, :edit, :update, :destroy, :upvote]
  before_filter :check_if_admin, only:[:new, :edit, :update, :destroy, :create]
  def index
    @items=Item
    @items = Item.where('price >= ? ', params[:price_from]) if params[:price_from]
    @items = @items.where('created_at >=?', 1.day.ago) if params[:today]
    @items = @items.where('votes_count >=?',params[:votes_count]) if params[:votes_from]
    @items=@items.order('votes_count DESC', 'price').limit(10)
      #@items = Item.order
  end
  def new
    @item = Item.new
  end
  #items Post
  def expensive
    @items = Item.where("price>100")
    render "index"
  end
  def create
    @item = Item.create(params[:item])
    if @item.errors.empty?
       redirect_to item_path(@item)
    else
      flash[:error] = "you make mistake"
       render "new"
    end
  end

  #items/new Get

  #items/id Get
  def show
      unless @item
           render  text:  "Page not found" , status: 404
      end
  end

  #items/id Get
  def edit
    @session = GoogleDrive.login("yuriybogash93@gmail.com", "Master720")
    @app_version = @session.spreadsheet_by_key("0AuO1PubF79WadFc2ZWJoeG4wV00wNThGVGZKVFZJWHc").worksheet_by_title("total")
    @line=[]
    (3..10).each do |d|
      @line[d-3]=[@app_version[d,1],@app_version[d,5].to_i]
    end
    p @line
  end
  #items/id PUT
  def update
    @item.update_attributes(params[:item])
    if @item.errors.empty?
      redirect_to item_path(@item)
    else
      flash[:error] = "#{@line.to_s}test"
      render "edit"
    end
  end
  #items/id DELETE
  def destroy
    @item.destroy
    redirect_to "/items"
  end
  def upvote
      @item.increment!(:votes_count)
      redirect_to action:  :index
  end
  private

  def find_item
    @item = Item.where(id: params[:id]).first
    render_404 unless @item
  end



end

app/helpers/application_helper.rb
module ApplicationHelper

  def urls_to_images (s1)
   raw s1.gsub /\s(http:\/\/.*?\.(png|jpg))\s/, '<p><img width=200 height =100 src="\1"/></p>'


   end
  def urls_to_link (s1)
   raw s1.gsub /\s(http:\/\/.*?)\s/, '<p><a href="\1">\1</a></p>'

  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= form_for @item do |f| %>
    <%= render partial: "share/form", locals: {f: f} %>
    <p> <%= f.submit "Save changes" %> </p>
<% end %>

app/views/items/index.html.erb
<% if@items.empty? %>
    <b>No items in store</b>
<% else %>
<table>
  <tr>
    <th>item id</th>
    <th>Name</th>
    <th>Price</th>
    <th> </th>
    <th> </th>
    <th> </th>
    <th> </th>
  </tr>




<% @items.each do |i| %>
   <tr>
     <td><%= i.id %></td>
     <td><%= link_to i.name, item_path(i) %></td>
     <td><%= i.price %></td>
     <td><%= link_to "Edit", "#{item_path(i)}"+"/edit" %></td>
     <td><%= link_to "Delete", i, method: :delete, data:{confirm:"Are you sure?"}%></td>
     <td>Rate: <%= i.votes_count %> <%= link_to "+", upvote_item_path(i) %> </td>
   </tr>

<% end %>
</table>

<% end %>
<br/>
<%= link_to "Add new item", "/items/new" %>

app/views/items/new.html.erb
<h1>Create New Item</h1>

<%= form_for @item do |f| %>
    <%= render partial: "share/form", locals: {f: f} %>
    <p> <%= f.submit "Create item" %> </p>
<% end %>

app/views/items/show.html.haml
%h3 Show

%h1= @item.name

%ul
    %li= urls_to_link (urls_to_images(@item.description))
    %li=@item.price
    %li=@item.weight

%h2=link_to "Edit", "#{item_path(@item)}"+"/edit"

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Modern
Description: A two-column, fixed-width design.
Version    : 1.0
Released   : 20080608

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>MyStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jqplot" %>
  <script type="text/javascript" language="javascript" src="jqplot.dateAxisRenderer.js"></script>
  <%= csrf_meta_tags %>
  <script>
      $(function(){
          2
          $.jqplot("example",  [ [
              3
                      [0,0], [1,2],
              4
                      [3,5.12], [5,13.1],
              5
                      [7,33.6], [9,85.9],
              6
                      [11,219.9]
              7
          ] ], {legend: {show: true}});
          8
      });



  </script>
</head>
<body>


<div id="wrapper">
  <div id="wrapper-top">
    <div id="wrapper-btm">

      <!-- start header -->
      <div id="header">
        <h1>Modern </h1>
        <p> design By Free CSS Templates</p>
      </div>
      <!-- end header -->
      <!-- start page -->

      <div id="page">
        <div class="bgtop">
          <div class="bgbtm">
            <!-- start content -->
            <div id="content">
              <div class="post">

                <div id="example" style="height:320px; width:400px; color:greenyellow" ><%= jqplot 300, 600, @line, {
                        title:'Customized Date Axis',
                        axes:{
                                xaxis:{
                                        renderer:jqplot.DateAxisRenderer
                                                                                            }
                                                                                            } ,
                      legend: {show: true}} %></div>
                <center> <%= yield %></center>
               </div>
            </div>
            <!-- end content -->

            <!-- start sidebar -->
            <div id="sidebar">
              <ul>
                <li>
                  <h2>Main menu</h2>
                  <ul>
                    <li> <%= link_to "Home Page", "/items" %></li>

                  </ul>
                </li>
                <li>
                  <h2>Categories</h2>
                  <ul>
                    <li><a href="#">Aliquam liberonare</a></li>
                    <li><a href="#">Consectetuer adipiscing</a></li>
                    <li><a href="#">Metusin  pellentesque</a></li>
                    <li><a href="#">Suspendisse  maurisres</a></li>
                    <li><a href="#">Urnanet  molestie semper</a></li>
                    <li><a href="#">Proin gravida  porttitor</a></li>
                  </ul>
                </li>
                <li>
                  <h2>Blogroll</h2>
                  <ul>
                    <li><a href="#">Aliquam liberonare</a></li>
                    <li><a href="#">Consectetuer adipiscing</a></li>
                    <li><a href="#">Metusin  pellentesque</a></li>
                    <li><a href="#">Suspendisse  maurisres</a></li>
                    <li><a href="#">Urnanet  molestie semper</a></li>
                    <li><a href="#">Proin gravida  porttitor</a></li>
                  </ul>
                </li>
                <li>
                  <h2>Lorem Ipsum Dolor</h2>
                  <ul>
                    <li><a href="#">Aliquam liberonare</a></li>
                    <li><a href="#">Consectetuer adipiscing</a></li>
                    <li><a href="#">Metusin  pellentesque</a></li>
                    <li><a href="#">Proin gravida  porttitor</a></li>
                  </ul>
                </li>
                <li>
                  <h2>Archives</h2>
                  <ul>
                    <li><a href="#">September</a> (23)</li>
                    <li><a href="#">August</a> (31)</li>
                    <li><a href="#">July</a> (31)</li>
                    <li><a href="#">June</a> (30)</li>
                    <li><a href="#">May</a> (31)</li>
                    <li><a href="#">April</a> (30)</li>
                  </ul>
                </li>
              </ul>
            </div>
            <!-- end sidebar -->
            <div style="clear:both">&nbsp;</div>
          </div>
        </div>
      </div>

      <div id="footer">
        <p>&copy;2013 All Rights Reserved &nbsp;&bull;&nbsp; Design by <a href="https://vk.com/id21546679">Yuriy Bogash</a> &nbsp;&bull;&nbsp;			<div style="display:none;"></div>
        </p>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/share/_form.html.erb
<p style="color: red; "><%= flash[:error] %> </p>
<p>Price<br/> <%= f.text_field :price  %>  </p>
<p>Name</p> <%= f.text_field :name  %>      </p>
<p>Description</p> <%= f.text_area :description  %>  </p>
<p>Weight</p> <%= f.text_field :weight  %> </p>